module.exports={
    userFormateError:{
        code:'10001',
        message:'用户名或密码为空',
        result:''
    },
    userAlreadyExisted:{
        code:'10002',
        message:'用户已存在',
        result:''
    },
    userRegisterError:{
        code:'10003',
        message:'用户注册失败',
        result:''
    },
    userDoesNotExisted:{
        code:'10004',
        message:'用户不存在',
        result:''
    },
    userInvalidPassword:{
        code:'10005',
        message:'无效密码',
        result:''
    },
    userLoginError:{
        code:'10006',
        message:'用户登陆失败',
        result:''
    },
    tokenExpiredError:{
        code:'10101',
        message:'Token过期',
        result:''
    },
    jsonWebTokenError:{
        code:'10102',
        message:'无效Token',
        result:''
    },
    tokenIsNotNull:{
        code:'10103',
        message:'Token为空，请登陆',
        result:''
    },
    hasNotAdminPermissions:{
        code:'10104',
        message:'没有管理员权限',
        result:''
    }
}
